/*-------------------------------------------------------------------------
 *
 * kmd_replication_origin_d.h
 *    Macro definitions for kmd_replication_origin
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_REPLICATION_ORIGIN_D_H
#define KMD_REPLICATION_ORIGIN_D_H

#define ReplicationOriginRelationId 6000

#define Anum_kmd_replication_origin_roident 1
#define Anum_kmd_replication_origin_roname 2

#define Natts_kmd_replication_origin 2


#endif							/* KMD_REPLICATION_ORIGIN_D_H */
