/*-------------------------------------------------------------------------
 *
 * kmd_conversion_d.h
 *    Macro definitions for kmd_conversion
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_CONVERSION_D_H
#define KMD_CONVERSION_D_H

#define ConversionRelationId 2607

#define Anum_kmd_conversion_oid 1
#define Anum_kmd_conversion_conname 2
#define Anum_kmd_conversion_connamespace 3
#define Anum_kmd_conversion_conowner 4
#define Anum_kmd_conversion_conforencoding 5
#define Anum_kmd_conversion_contoencoding 6
#define Anum_kmd_conversion_conproc 7
#define Anum_kmd_conversion_condefault 8

#define Natts_kmd_conversion 8


#endif							/* KMD_CONVERSION_D_H */
