/*-------------------------------------------------------------------------
 *
 * kmd_description_d.h
 *    Macro definitions for kmd_description
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_DESCRIPTION_D_H
#define KMD_DESCRIPTION_D_H

#define DescriptionRelationId 2609

#define Anum_kmd_description_objoid 1
#define Anum_kmd_description_classoid 2
#define Anum_kmd_description_objsubid 3
#define Anum_kmd_description_description 4

#define Natts_kmd_description 4


#endif							/* KMD_DESCRIPTION_D_H */
