/*-------------------------------------------------------------------------
 *
 * kmd_publication_d.h
 *    Macro definitions for kmd_publication
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_PUBLICATION_D_H
#define KMD_PUBLICATION_D_H

#define PublicationRelationId 6104

#define Anum_kmd_publication_oid 1
#define Anum_kmd_publication_pubname 2
#define Anum_kmd_publication_pubowner 3
#define Anum_kmd_publication_puballtables 4
#define Anum_kmd_publication_pubinsert 5
#define Anum_kmd_publication_pubupdate 6
#define Anum_kmd_publication_pubdelete 7
#define Anum_kmd_publication_pubtruncate 8

#define Natts_kmd_publication 8


#endif							/* KMD_PUBLICATION_D_H */
