/*-------------------------------------------------------------------------
 *
 * kmd_amproc_d.h
 *    Macro definitions for kmd_amproc
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_AMPROC_D_H
#define KMD_AMPROC_D_H

#define AccessMethodProcedureRelationId 2603

#define Anum_kmd_amproc_oid 1
#define Anum_kmd_amproc_amprocfamily 2
#define Anum_kmd_amproc_amproclefttype 3
#define Anum_kmd_amproc_amprocrighttype 4
#define Anum_kmd_amproc_amprocnum 5
#define Anum_kmd_amproc_amproc 6

#define Natts_kmd_amproc 6


#endif							/* KMD_AMPROC_D_H */
