/*-------------------------------------------------------------------------
 *
 * kmd_opfamily_d.h
 *    Macro definitions for kmd_opfamily
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_OPFAMILY_D_H
#define KMD_OPFAMILY_D_H

#define OperatorFamilyRelationId 2753

#define Anum_kmd_opfamily_oid 1
#define Anum_kmd_opfamily_opfmethod 2
#define Anum_kmd_opfamily_opfname 3
#define Anum_kmd_opfamily_opfnamespace 4
#define Anum_kmd_opfamily_opfowner 5

#define Natts_kmd_opfamily 5


#define IsBooleanOpfamily(opfamily) \
	((opfamily) == BOOL_BTREE_FAM_OID || (opfamily) == BOOL_HASH_FAM_OID)

#define BOOL_BTREE_FAM_OID 424
#define BPCHAR_BTREE_FAM_OID 426
#define BYTEA_BTREE_FAM_OID 428
#define NETWORK_BTREE_FAM_OID 1974
#define INTEGER_BTREE_FAM_OID 1976
#define OID_BTREE_FAM_OID 1989
#define TEXT_BTREE_FAM_OID 1994
#define TEXT_PATTERN_BTREE_FAM_OID 2095
#define BPCHAR_PATTERN_BTREE_FAM_OID 2097
#define BOOL_HASH_FAM_OID 2222
#define TEXT_SPGIST_FAM_OID 4017

#endif							/* KMD_OPFAMILY_D_H */
