/*-------------------------------------------------------------------------
 *
 * kmd_enum_d.h
 *    Macro definitions for kmd_enum
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_ENUM_D_H
#define KMD_ENUM_D_H

#define EnumRelationId 3501

#define Anum_kmd_enum_oid 1
#define Anum_kmd_enum_enumtypid 2
#define Anum_kmd_enum_enumsortorder 3
#define Anum_kmd_enum_enumlabel 4

#define Natts_kmd_enum 4


#endif							/* KMD_ENUM_D_H */
