/*-------------------------------------------------------------------------
 *
 * kmd_rewrite_d.h
 *    Macro definitions for kmd_rewrite
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_REWRITE_D_H
#define KMD_REWRITE_D_H

#define RewriteRelationId 2618

#define Anum_kmd_rewrite_oid 1
#define Anum_kmd_rewrite_rulename 2
#define Anum_kmd_rewrite_ev_class 3
#define Anum_kmd_rewrite_ev_type 4
#define Anum_kmd_rewrite_ev_enabled 5
#define Anum_kmd_rewrite_is_instead 6
#define Anum_kmd_rewrite_ev_qual 7
#define Anum_kmd_rewrite_ev_action 8

#define Natts_kmd_rewrite 8


#endif							/* KMD_REWRITE_D_H */
