/*-------------------------------------------------------------------------
 *
 * kmd_range_d.h
 *    Macro definitions for kmd_range
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_RANGE_D_H
#define KMD_RANGE_D_H

#define RangeRelationId 3541

#define Anum_kmd_range_rngtypid 1
#define Anum_kmd_range_rngsubtype 2
#define Anum_kmd_range_rngcollation 3
#define Anum_kmd_range_rngsubopc 4
#define Anum_kmd_range_rngcanonical 5
#define Anum_kmd_range_rngsubdiff 6

#define Natts_kmd_range 6


#endif							/* KMD_RANGE_D_H */
