/*-------------------------------------------------------------------------
 *
 * kmd_shdescription_d.h
 *    Macro definitions for kmd_shdescription
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_SHDESCRIPTION_D_H
#define KMD_SHDESCRIPTION_D_H

#define SharedDescriptionRelationId 2396

#define Anum_kmd_shdescription_objoid 1
#define Anum_kmd_shdescription_classoid 2
#define Anum_kmd_shdescription_description 3

#define Natts_kmd_shdescription 3


#endif							/* KMD_SHDESCRIPTION_D_H */
