/*-------------------------------------------------------------------------
 *
 * kmd_policy_d.h
 *    Macro definitions for kmd_policy
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_POLICY_D_H
#define KMD_POLICY_D_H

#define PolicyRelationId 3256

#define Anum_kmd_policy_oid 1
#define Anum_kmd_policy_polname 2
#define Anum_kmd_policy_polrelid 3
#define Anum_kmd_policy_polcmd 4
#define Anum_kmd_policy_polpermissive 5
#define Anum_kmd_policy_polroles 6
#define Anum_kmd_policy_polqual 7
#define Anum_kmd_policy_polwithcheck 8

#define Natts_kmd_policy 8


#endif							/* KMD_POLICY_D_H */
