/*-------------------------------------------------------------------------
 *
 * kmd_ts_config_d.h
 *    Macro definitions for kmd_ts_config
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_TS_CONFIG_D_H
#define KMD_TS_CONFIG_D_H

#define TSConfigRelationId 3602

#define Anum_kmd_ts_config_oid 1
#define Anum_kmd_ts_config_cfgname 2
#define Anum_kmd_ts_config_cfgnamespace 3
#define Anum_kmd_ts_config_cfgowner 4
#define Anum_kmd_ts_config_cfgparser 5

#define Natts_kmd_ts_config 5


#endif							/* KMD_TS_CONFIG_D_H */
