/*-------------------------------------------------------------------------
 *
 * kmd_tablespace_d.h
 *    Macro definitions for kmd_tablespace
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_TABLESPACE_D_H
#define KMD_TABLESPACE_D_H

#define TableSpaceRelationId 1213

#define Anum_kmd_tablespace_oid 1
#define Anum_kmd_tablespace_spcname 2
#define Anum_kmd_tablespace_spcowner 3
#define Anum_kmd_tablespace_spcacl 4
#define Anum_kmd_tablespace_spcoptions 5

#define Natts_kmd_tablespace 5

#define DEFAULTTABLESPACE_OID 1663
#define GLOBALTABLESPACE_OID 1664

#endif							/* KMD_TABLESPACE_D_H */
