/*-------------------------------------------------------------------------
 *
 * kmd_publication_rel_d.h
 *    Macro definitions for kmd_publication_rel
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_PUBLICATION_REL_D_H
#define KMD_PUBLICATION_REL_D_H

#define PublicationRelRelationId 6106

#define Anum_kmd_publication_rel_oid 1
#define Anum_kmd_publication_rel_prpubid 2
#define Anum_kmd_publication_rel_prrelid 3

#define Natts_kmd_publication_rel 3


#endif							/* KMD_PUBLICATION_REL_D_H */
