/*-------------------------------------------------------------------------
 *
 * kmd_largeobject_d.h
 *    Macro definitions for kmd_largeobject
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_LARGEOBJECT_D_H
#define KMD_LARGEOBJECT_D_H

#define LargeObjectRelationId 2613

#define Anum_kmd_largeobject_loid 1
#define Anum_kmd_largeobject_pageno 2
#define Anum_kmd_largeobject_data 3

#define Natts_kmd_largeobject 3


#endif							/* KMD_LARGEOBJECT_D_H */
