/*-------------------------------------------------------------------------
 *
 * kmd_statistic_ext_data_d.h
 *    Macro definitions for kmd_statistic_ext_data
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_STATISTIC_EXT_DATA_D_H
#define KMD_STATISTIC_EXT_DATA_D_H

#define StatisticExtDataRelationId 3429

#define Anum_kmd_statistic_ext_data_stxoid 1
#define Anum_kmd_statistic_ext_data_stxdndistinct 2
#define Anum_kmd_statistic_ext_data_stxddependencies 3
#define Anum_kmd_statistic_ext_data_stxdmcv 4

#define Natts_kmd_statistic_ext_data 4


#endif							/* KMD_STATISTIC_EXT_DATA_D_H */
