/*-------------------------------------------------------------------------
 *
 * kmd_user_mapping_d.h
 *    Macro definitions for kmd_user_mapping
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_USER_MAPPING_D_H
#define KMD_USER_MAPPING_D_H

#define UserMappingRelationId 1418

#define Anum_kmd_user_mapping_oid 1
#define Anum_kmd_user_mapping_umuser 2
#define Anum_kmd_user_mapping_umserver 3
#define Anum_kmd_user_mapping_umoptions 4

#define Natts_kmd_user_mapping 4


#endif							/* KMD_USER_MAPPING_D_H */
