/*-------------------------------------------------------------------------
 *
 * kmd_ts_parser_d.h
 *    Macro definitions for kmd_ts_parser
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_TS_PARSER_D_H
#define KMD_TS_PARSER_D_H

#define TSParserRelationId 3601

#define Anum_kmd_ts_parser_oid 1
#define Anum_kmd_ts_parser_prsname 2
#define Anum_kmd_ts_parser_prsnamespace 3
#define Anum_kmd_ts_parser_prsstart 4
#define Anum_kmd_ts_parser_prstoken 5
#define Anum_kmd_ts_parser_prsend 6
#define Anum_kmd_ts_parser_prsheadline 7
#define Anum_kmd_ts_parser_prslextype 8

#define Natts_kmd_ts_parser 8


#endif							/* KMD_TS_PARSER_D_H */
