/*-------------------------------------------------------------------------
 *
 * kmd_database_d.h
 *    Macro definitions for kmd_database
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_DATABASE_D_H
#define KMD_DATABASE_D_H

#define DatabaseRelationId 1262
#define DatabaseRelation_Rowtype_Id 1248

#define Anum_kmd_database_oid 1
#define Anum_kmd_database_datname 2
#define Anum_kmd_database_datdba 3
#define Anum_kmd_database_encoding 4
#define Anum_kmd_database_datcollate 5
#define Anum_kmd_database_datctype 6
#define Anum_kmd_database_datistemplate 7
#define Anum_kmd_database_datallowconn 8
#define Anum_kmd_database_datconnlimit 9
#define Anum_kmd_database_datlastsysoid 10
#define Anum_kmd_database_datfrozenxid 11
#define Anum_kmd_database_datminmxid 12
#define Anum_kmd_database_dattablespace 13
#define Anum_kmd_database_datacl 14

#define Natts_kmd_database 14

#define TemplateDbOid 1

#endif							/* KMD_DATABASE_D_H */
