/*-------------------------------------------------------------------------
 *
 * kmd_db_role_setting_d.h
 *    Macro definitions for kmd_db_role_setting
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_DB_ROLE_SETTING_D_H
#define KMD_DB_ROLE_SETTING_D_H

#define DbRoleSettingRelationId 2964

#define Anum_kmd_db_role_setting_setdatabase 1
#define Anum_kmd_db_role_setting_setrole 2
#define Anum_kmd_db_role_setting_setconfig 3

#define Natts_kmd_db_role_setting 3


#endif							/* KMD_DB_ROLE_SETTING_D_H */
