/*-------------------------------------------------------------------------
 *
 * kmd_ts_config_map_d.h
 *    Macro definitions for kmd_ts_config_map
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_TS_CONFIG_MAP_D_H
#define KMD_TS_CONFIG_MAP_D_H

#define TSConfigMapRelationId 3603

#define Anum_kmd_ts_config_map_mapcfg 1
#define Anum_kmd_ts_config_map_maptokentype 2
#define Anum_kmd_ts_config_map_mapseqno 3
#define Anum_kmd_ts_config_map_mapdict 4

#define Natts_kmd_ts_config_map 4


#endif							/* KMD_TS_CONFIG_MAP_D_H */
