/*-------------------------------------------------------------------------
 *
 * kmd_inherits_d.h
 *    Macro definitions for kmd_inherits
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_INHERITS_D_H
#define KMD_INHERITS_D_H

#define InheritsRelationId 2611

#define Anum_kmd_inherits_inhrelid 1
#define Anum_kmd_inherits_inhparent 2
#define Anum_kmd_inherits_inhseqno 3

#define Natts_kmd_inherits 3


#endif							/* KMD_INHERITS_D_H */
