/*-------------------------------------------------------------------------
 *
 * kmd_namespace_d.h
 *    Macro definitions for kmd_namespace
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_NAMESPACE_D_H
#define KMD_NAMESPACE_D_H

#define NamespaceRelationId 2615

#define Anum_kmd_namespace_oid 1
#define Anum_kmd_namespace_nspname 2
#define Anum_kmd_namespace_nspowner 3
#define Anum_kmd_namespace_nspacl 4

#define Natts_kmd_namespace 4

#define PG_CATALOG_NAMESPACE 11
#define PG_TOAST_NAMESPACE 99
#define PG_PUBLIC_NAMESPACE 2200

#endif							/* KMD_NAMESPACE_D_H */
