/*-------------------------------------------------------------------------
 *
 * kmd_sequence_d.h
 *    Macro definitions for kmd_sequence
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_SEQUENCE_D_H
#define KMD_SEQUENCE_D_H

#define SequenceRelationId 2224

#define Anum_kmd_sequence_seqrelid 1
#define Anum_kmd_sequence_seqtypid 2
#define Anum_kmd_sequence_seqstart 3
#define Anum_kmd_sequence_seqincrement 4
#define Anum_kmd_sequence_seqmax 5
#define Anum_kmd_sequence_seqmin 6
#define Anum_kmd_sequence_seqcache 7
#define Anum_kmd_sequence_seqcycle 8

#define Natts_kmd_sequence 8


#endif							/* KMD_SEQUENCE_D_H */
