/*-------------------------------------------------------------------------
 *
 * kmd_amop_d.h
 *    Macro definitions for kmd_amop
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_AMOP_D_H
#define KMD_AMOP_D_H

#define AccessMethodOperatorRelationId 2602

#define Anum_kmd_amop_oid 1
#define Anum_kmd_amop_amopfamily 2
#define Anum_kmd_amop_amoplefttype 3
#define Anum_kmd_amop_amoprighttype 4
#define Anum_kmd_amop_amopstrategy 5
#define Anum_kmd_amop_amoppurpose 6
#define Anum_kmd_amop_amopopr 7
#define Anum_kmd_amop_amopmethod 8
#define Anum_kmd_amop_amopsortfamily 9

#define Natts_kmd_amop 9


/* allowed values of amoppurpose: */
#define AMOP_SEARCH		's'		/* operator is for search */
#define AMOP_ORDER		'o'		/* operator is for ordering */


#endif							/* KMD_AMOP_D_H */
