/*-------------------------------------------------------------------------
 *
 * kmd_depend_d.h
 *    Macro definitions for kmd_depend
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_DEPEND_D_H
#define KMD_DEPEND_D_H

#define DependRelationId 2608

#define Anum_kmd_depend_classid 1
#define Anum_kmd_depend_objid 2
#define Anum_kmd_depend_objsubid 3
#define Anum_kmd_depend_refclassid 4
#define Anum_kmd_depend_refobjid 5
#define Anum_kmd_depend_refobjsubid 6
#define Anum_kmd_depend_deptype 7

#define Natts_kmd_depend 7


#endif							/* KMD_DEPEND_D_H */
