/*-------------------------------------------------------------------------
 *
 * kmd_shdepend_d.h
 *    Macro definitions for kmd_shdepend
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_SHDEPEND_D_H
#define KMD_SHDEPEND_D_H

#define SharedDependRelationId 1214

#define Anum_kmd_shdepend_dbid 1
#define Anum_kmd_shdepend_classid 2
#define Anum_kmd_shdepend_objid 3
#define Anum_kmd_shdepend_objsubid 4
#define Anum_kmd_shdepend_refclassid 5
#define Anum_kmd_shdepend_refobjid 6
#define Anum_kmd_shdepend_deptype 7

#define Natts_kmd_shdepend 7


#endif							/* KMD_SHDEPEND_D_H */
