/*-------------------------------------------------------------------------
 *
 * kmd_transform_d.h
 *    Macro definitions for kmd_transform
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_TRANSFORM_D_H
#define KMD_TRANSFORM_D_H

#define TransformRelationId 3576

#define Anum_kmd_transform_oid 1
#define Anum_kmd_transform_trftype 2
#define Anum_kmd_transform_trflang 3
#define Anum_kmd_transform_trffromsql 4
#define Anum_kmd_transform_trftosql 5

#define Natts_kmd_transform 5


#endif							/* KMD_TRANSFORM_D_H */
