/*-------------------------------------------------------------------------
 *
 * kmd_seclabel_d.h
 *    Macro definitions for kmd_seclabel
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_SECLABEL_D_H
#define KMD_SECLABEL_D_H

#define SecLabelRelationId 3596

#define Anum_kmd_seclabel_objoid 1
#define Anum_kmd_seclabel_classoid 2
#define Anum_kmd_seclabel_objsubid 3
#define Anum_kmd_seclabel_provider 4
#define Anum_kmd_seclabel_label 5

#define Natts_kmd_seclabel 5


#endif							/* KMD_SECLABEL_D_H */
