/*-------------------------------------------------------------------------
 *
 * kmd_attrdef_d.h
 *    Macro definitions for kmd_attrdef
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_ATTRDEF_D_H
#define KMD_ATTRDEF_D_H

#define AttrDefaultRelationId 2604

#define Anum_kmd_attrdef_oid 1
#define Anum_kmd_attrdef_adrelid 2
#define Anum_kmd_attrdef_adnum 3
#define Anum_kmd_attrdef_adbin 4

#define Natts_kmd_attrdef 4


#endif							/* KMD_ATTRDEF_D_H */
