/*-------------------------------------------------------------------------
 *
 * kmd_subscription_d.h
 *    Macro definitions for kmd_subscription
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef KMD_SUBSCRIPTION_D_H
#define KMD_SUBSCRIPTION_D_H

#define SubscriptionRelationId 6100
#define SubscriptionRelation_Rowtype_Id 6101

#define Anum_kmd_subscription_oid 1
#define Anum_kmd_subscription_subdbid 2
#define Anum_kmd_subscription_subname 3
#define Anum_kmd_subscription_subowner 4
#define Anum_kmd_subscription_subenabled 5
#define Anum_kmd_subscription_subconninfo 6
#define Anum_kmd_subscription_subslotname 7
#define Anum_kmd_subscription_subsynccommit 8
#define Anum_kmd_subscription_subpublications 9

#define Natts_kmd_subscription 9


#endif							/* KMD_SUBSCRIPTION_D_H */
